### ISSUE TITLE
Exception when trying to explore english model

### ISSUE THREAD

**Issue by grivescorbett** [idio/spotlight-model-editor#12]
This is the command I ran: `sh target/bin/model-editor explore /path/to/en2+2/model/ 40`
and the error output:

```
   Exception in thread "main" com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 12
at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:113)
at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:613)
at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:724)
at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:139)
at org.dbpedia.spotlight.db.memory.MemoryStore$.loadSurfaceFormStore(MemoryStore.scala:152)
at org.idio.dbpedia.spotlight.stores.CustomSurfaceFormStore.<init>(CustomSurfaceFormStore.scala:31)
at org.idio.dbpedia.spotlight.CustomSpotlightModel.liftedTree3$1(CustomSpotlightModel.scala:75)
at org.idio.dbpedia.spotlight.CustomSpotlightModel.customSurfaceFormStore(CustomSpotlightModel.scala:73)
at org.idio.dbpedia.spotlight.CustomSpotlightModel.showSomeSurfaceForms(CustomSpotlightModel.scala:333)
at org.idio.dbpedia.spotlight.Main$.runCommand(SpotlightModelReader.scala:180)
at org.idio.dbpedia.spotlight.Main$.main(SpotlightModelReader.scala:40)
at org.idio.dbpedia.spotlight.Main.main(SpotlightModelReader.scala)
```

Any advice would be appreciated.

**Comment by dav009** [comment]
Could you confirm the version of Spotlight model(0.7 or 0.6)?

the master branch works for Spotlight0.6's models

**Comment by grivescorbett** [comment]
Ahh my apologies, I've switched over to the 0.7 feature branch and seem to be in good shape.  Thanks!
