### ISSUE TITLE
KryoException loading MemorySurfaceFormStore

### ISSUE THREAD

**Issue by sam-k3nny** [idio/spotlight-model-editor#23]
I've built spotlight-model-editor on two separate machines with lots of memory. The builds have been successful, and I can 'remove' 'associations'. I cannot, however, make surface forms unspottable or even explore. I get the following exception below.

I am using Java 1.7.0_80 and Scala 1.9.3. Does anyone have any ideas or suggestions, please?

sh ../spotlight-model-editor/target/bin/model-editor explore en/model 20

`Apr 24, 2017 4:17:56 PM org.dbpedia.spotlight.db.memory.MemoryStore$ load
INFO: Loading MemorySurfaceFormStore...
Exception in thread "main" com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 12
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:113)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:613)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:724)
        at org.dbpedia.spotlight.db.memory.MemoryStore$.load(MemoryStore.scala:139)
        at org.dbpedia.spotlight.db.memory.MemoryStore$.loadSurfaceFormStore(MemoryStore.scala:152)
        at org.idio.dbpedia.spotlight.stores.CustomSurfaceFormStore.<init>(CustomSurfaceFormStore.scala:31)
        at org.idio.dbpedia.spotlight.CustomSpotlightModel.liftedTree3$1(CustomSpotlightModel.scala:75)
        at org.idio.dbpedia.spotlight.CustomSpotlightModel.customSurfaceFormStore(CustomSpotlightModel.scala:73)
        at org.idio.dbpedia.spotlight.CustomSpotlightModel.showSomeSurfaceForms(CustomSpotlightModel.scala:333)
        at org.idio.dbpedia.spotlight.Main$.runCommand(SpotlightModelReader.scala:180)
        at org.idio.dbpedia.spotlight.Main$.main(SpotlightModelReader.scala:40)
        at org.idio.dbpedia.spotlight.Main.main(SpotlightModelReader.scala)`

**Comment by sam-k3nny** [comment]
Figured out that I needed to use this model - http://spotlight.sztaki.hu/downloads/latest_models/en.tar.gz NOT http://downloads.dbpedia-spotlight.org/en/ and dav009's branch - https://github.com/dav009/spotlight-model-editor
